### ISSUE TITLE
 TypeError: $ is not a function.

### ISSUE THREAD

**Issue by hakunamatata97k** [forwardemail/custom-fonts-in-emails#8]
## Describe the bug

**Node.js version:**  v16.15.1 

**Description:** TypeError: $ is not a function. 

## Actual behavior
I installed a custom font  called ```Camelina.otf ``` and placed it in the path `/usr/share/font/opentype/` then `sudo fc-cache -f -v` to update the font cache. 
to check if the font in installed or not i tested it with the following code: 

```
import  osFonts from 'os-fonts';
osFonts.getAll().then(fonts => {
    // array of fonts...
    fonts.forEach(font => {
        console.log(font);
    });
})

```
and i could indeed see that the font exists under the `/usr/share/font/opentype/Camelina.otf`
after following the guide from your readme i tried to run the program and i always get the error: 
```

TypeError: $ is not a function
    at svg (/home/kazem/WebstormProjects/x/node_modules/custom-fonts-in-emails/lib/index.js:173:14)
    at async png (/home/kazem/WebstormProjects/x/node_modules/custom-fonts-in-emails/lib/index.js:240:18)
```

## Code to reproduce
Saved it as `t.mjs` and ran it with `node t.mjs`
```
import customFonts from 'custom-fonts-in-emails';
import path from 'path';

const options = {
  text: 'Make something people want',
  fontNameOrPath: 'Camelina',
  fontColor: 'white',
  backgroundColor: '#ff6600',
  fontSize: 40
};

customFonts.png2x(options)
  .then(console.log)
  .catch(console.error);
```

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by titanism** [comment]
We will review and follow up soon

**Comment by titanism** [comment]
v5.0.0 released which fixes the issue <https://github.com/forwardemail/custom-fonts-in-emails/releases/tag/v5.0.0>

The core issue was that they did a new release of `cheerio` to npm and they changed the exports from `const $ = require('cheerio')` to `const $ = require('cheerio').default`... unfortunately this bad practice still happens in the community.
